CXX = x86_64-w64-mingw32-g++
CXXFLAGS_BASE = -std=c++17 -O3 -march=x86-64 -mtune=generic -static -static-libgcc -static-libstdc++ -s -flto -Wl,--stack,16777216 
INCLUDES = -I. -Iaes
LIBS = -lwinpthread -lz 

AVX2_ON = no

ifeq ($(AVX2_ON), yes)
    CXXFLAGS = $(CXXFLAGS_BASE) -march=x86-64-v3 -mavx2 -mfma
else
    CXXFLAGS = $(CXXFLAGS_BASE)
endif

TARGET = oodleforge.exe
SOURCES = main.cpp common.cpp scan.cpp encode.cpp reconstruct.cpp aes.c

all: $(TARGET)

$(TARGET): $(SOURCES)
	@echo "Building with AVX2=$(AVX2_ON)"
	$(CXX) $(CXXFLAGS) $(INCLUDES) $^ -o $@ $(LIBS)

clean:
	rm -f $(TARGET)

.PHONY: all clean
