# Linux Makefile for OodleForge v34 (Legendary Edition)
CXX = g++
CXXFLAGS = -std=c++17 -O3 -march=x86-64 -mtune=generic -flto -Wall -Wextra -s
INCLUDES = -I. -Iaes 
LIBS = -lpthread -ldl -static-libgcc -static-libstdc++ -lz 

TARGET = oodleforge-amd64
SOURCES = main.cpp common.cpp scan.cpp encode.cpp reconstruct.cpp aes.c

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(CXX) $(CXXFLAGS) $(INCLUDES) $^ -o $@ $(LIBS)

clean:
	rm -f $(TARGET)

.PHONY: all clean
