CXX = g++
CXXFLAGS = -std=c++17 -O3 -march=x86-64-v3 -mtune=generic -flto -Wall -Wextra -s -mavx2 -mfma
# Or even more aggressive: -march=haswell or -march=znver3 (if targeting modern CPUs)
INCLUDES = -I. -Iaes 
LIBS = -lpthread -ldl -static-libgcc -static-libstdc++ -lz 

TARGET = oodleforge-amd64
SOURCES = main.cpp common.cpp scan.cpp encode.cpp reconstruct.cpp aes.c

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(CXX) $(CXXFLAGS) $(INCLUDES) $^ -o $@ $(LIBS)

clean:
	rm -f $(TARGET)

.PHONY: all clean
